name: pesel_validator
description: Dart package for PESEL number validation
version: 0.1.0
homepage: https://github.com/Stempnio/pesel-validator

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  quiver: ^3.1.0

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
