name: pesel_validator
description: A dart package for PESEL number validation. Allows to extract the data that is included in PESEL.
version: 0.1.1
homepage: https://github.com/Stempnio/pesel-validator

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  quiver: ^3.1.0

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ">=3.1.0 <5.0.0"
